version: "3.4"
services:
    openssh:
        image: harshavardhanj/openssh:debian
        ports:
            - "2222:22"
        environment:
            - USER=example
            - PASSWORD=example
